#!/usr/bin/env python3
"""Regenerate the artifact list in manifest.yaml, the INVENTORY in install.py and
the `render:` list in registry.yaml from the package tree, or check them (--check).

    python3 tests/gen_manifest.py          # rewrite the three generated blocks
    python3 tests/gen_manifest.py --check  # exit 1 if any block is stale

Artifacts are every file under skills/, agents/ and assets/ (sc-install copies files, not
directories). The render list is every artifact that contains an install-time
placeholder; .j2 dispatch templates are never rendered at install time.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG))
import install  # noqa: E402

CATEGORIES = ("skills", "agents", "assets")


def tree_artifacts() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for cat in CATEGORIES:
        files = [p for p in (PKG / cat).rglob("*") if p.is_file() and "node_modules" not in p.parts and "__pycache__" not in p.parts]
        out[cat] = sorted(str(p.relative_to(PKG)) for p in files)
    return out


def render_list(artifacts: dict[str, list[str]]) -> list[str]:
    out = []
    for cat in CATEGORIES:
        for rel in artifacts[cat]:
            if rel.endswith(".j2"):
                continue
            try:
                text = (PKG / rel).read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if install.PLACEHOLDER_RE.search(text):
                out.append(rel)
    return sorted(out)


def manifest_block(artifacts: dict[str, list[str]]) -> str:
    lines = ["artifacts:"]
    for cat in CATEGORIES:
        lines.append(f"  {cat}:")
        lines += [f"    - {rel}" for rel in artifacts[cat]]
    return "\n".join(lines) + "\n"


def replace_between(text: str, begin: str, end: str, body: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pattern.search(text):
        raise SystemExit(f"markers {begin!r}..{end!r} not found")
    return pattern.sub(lambda _: begin + "\n" + body + end, text, count=1)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    artifacts = tree_artifacts()
    renders = render_list(artifacts)

    targets = {
        PKG / "manifest.yaml": ("# ARTIFACTS-BEGIN (generated by tests/gen_manifest.py)", "# ARTIFACTS-END", manifest_block(artifacts)),
        PKG / "install.py": (
            "    # INVENTORY-BEGIN (generated from manifest.yaml by tests/gen_manifest.py)",
            "    # INVENTORY-END",
            "".join(f'    "{rel}",\n' for cat in CATEGORIES for rel in artifacts[cat]),
        ),
        PKG / "registry.yaml": ("# RENDER-BEGIN (generated by tests/gen_manifest.py)", "# RENDER-END", "render:\n" + "".join(f"  - {rel}\n" for rel in renders)),
    }
    stale = []
    for path, (begin, end, body) in targets.items():
        old = path.read_text(encoding="utf-8")
        new = replace_between(old, begin, end, body)
        if new != old:
            stale.append(path.name)
            if not check:
                path.write_text(new, encoding="utf-8")
    if check and stale:
        print("stale generated blocks: " + ", ".join(stale) + " (run tests/gen_manifest.py)")
        return 1
    print(f"artifacts: {sum(len(v) for v in artifacts.values())}, rendered at install: {len(renders)}"
          + (", rewritten: " + ", ".join(stale) if stale and not check else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
