#!/usr/bin/env python3
"""Write config/legacy-owned.json: the sha256 of every file the package shipped
before 0.4.0, which had no install record.

install.py uses it once per repository, on the first install that finds no
`.claude/project/atm-bd-orchestration.lock.json`: an existing file whose bytes
match one of these hashes (or the bytes this version ships) is a copy an earlier
install placed, so it is owned and replaced; any other existing file is not owned
and the install fails naming it. Delete this file, the generator and the
LEGACY_OWNED code path once no repository still carries a 0.x install without a
lock file.

The set is frozen: every commit on main that touched the package up to the last
pre-lock release (0.2.3, d5b7301). Rerun only to reproduce it:

    python3 tests/gen_legacy_owned.py
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
LAST_PRE_LOCK = "d5b7301"
PREFIX = "plugins/atm-bd-orchestration/"
SHIPPED = ("skills/", "agents/", "assets/scripts/")


def git(*args: str) -> bytes:
    return subprocess.run(["git", "-C", str(PKG), *args], check=True, stdout=subprocess.PIPE).stdout


def main() -> int:
    commits = git("rev-list", LAST_PRE_LOCK, "--", ":(top)" + PREFIX).decode().split()
    files: dict[str, set[str]] = {}
    for commit in commits:
        listing = git("ls-tree", "-r", "--full-tree", "--name-only", commit, "--", ":(top)" + PREFIX).decode().splitlines()
        for full in listing:
            rel = full[len(PREFIX):]
            if not rel.startswith(SHIPPED) or "/node_modules/" in rel or "__pycache__" in rel:
                continue
            data = git("show", f"{commit}:{full}")
            files.setdefault(rel, set()).add(hashlib.sha256(data).hexdigest())
    out = {
        "comment": "sha256 of every file shipped before the install record existed (<= 0.2.3); generated by tests/gen_legacy_owned.py",
        "through": LAST_PRE_LOCK,
        "files": {rel: sorted(shas) for rel, shas in sorted(files.items())},
    }
    (PKG / "config" / "legacy-owned.json").write_text(json.dumps(out, indent=1, sort_keys=False) + "\n", encoding="utf-8")
    print(f"{len(commits)} commits, {len(files)} paths, {sum(len(s) for s in files.values())} hashes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
